name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]

    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install mingw
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt install -y mingw-w64
      - name: Add Rust target
        run: |
          rustup target add $TARGET
        env:
          TARGET: ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: diffusion-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/diffusion*
