name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]

    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install mingw
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt install -y mingw-w64
      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Package binary
        run: |
          mkdir -p release
          if [[ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]; then
            cp target/${{ matrix.target }}/release/diffusion.exe release/diffusion-windows.exe
            zip -j release/diffusion-windows.zip release/diffusion-windows.exe
          elif [[ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]]; then
            cp target/${{ matrix.target }}/release/diffusion release/diffusion-linux
            zip -j release/diffusion-linux.zip release/diffusion-linux
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: release/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
